[package]
name = "game-driver-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1"
executor-api = { path = "../executor-api" }
serde.workspace = true
serde_json.workspace = true
snapshot-store = { path = "../snapshot-store" }
thiserror.workspace = true
