/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (DB reachable) */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Control-plane build version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/relay/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ed25519 public key used to sign relay tokens */
        get: operations["getRelayPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account. First user becomes operator. */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGroups"];
        put?: never;
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/v1/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch: operations["updateMember"];
        trace?: never;
    };
    "/v1/groups/{groupId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{code}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/enrollment-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEnrollmentTokens"];
        put?: never;
        post: operations["createEnrollmentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/enrollment-tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteEnrollmentToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device-links/{userCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeviceLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device-links/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveDeviceLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete: operations["deleteNode"];
        options?: never;
        head?: never;
        patch: operations["updateNode"];
        trace?: never;
    };
    "/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listServers"];
        put?: never;
        post: operations["createServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/servers/{serverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getServer"];
        put?: never;
        post?: never;
        delete: operations["deleteServer"];
        options?: never;
        head?: never;
        patch: operations["updateServer"];
        trace?: never;
    };
    "/v1/servers/{serverId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/servers/{serverId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/servers/{serverId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moveServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/servers/{serverId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSnapshots"];
        put?: never;
        post: operations["requestSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots/{snapshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSnapshot"];
        trace?: never;
    };
    "/v1/servers/{serverId}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/servers/{serverId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getServerLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/groups/{groupId}/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminSetGroupLimits"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/enroll/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start device-code enrollment (unsigned; no node yet). */
        post: operations["agentEnrollDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/enroll/device/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentEnrollDevicePoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/enroll/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentEnrollToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/executions/{executionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentExecutionStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/executions/{executionId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentExecutionLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentCreateSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/snapshots/{snapshotId}/replicas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentReplicaReady"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @enum {string} */
            code: "stale_epoch" | "latest_save_unavailable" | "not_found" | "forbidden" | "limit_exceeded" | "validation" | "unauthorized" | "conflict" | "unschedulable" | "internal";
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Version: {
            version: string;
        };
        RelayPublicKey: {
            /** @description base64 ed25519 public key */
            public_key: string;
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "member";
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
            /** @description required when signup policy is invite */
            invite_code?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            token: string;
        };
        User: {
            id: string;
            email: string;
            display_name: string;
            is_operator: boolean;
            /** Format: int64 */
            created_at: number;
        };
        Me: {
            user: components["schemas"]["User"];
            groups: {
                group_id: string;
                name: string;
                role: components["schemas"]["Role"];
            }[];
        };
        GroupSettings: {
            /** @default 120 */
            snapshot_interval_s: number;
            /** @default 3 */
            default_replication_factor: number;
            /** @default 2 */
            default_min_commit_replicas: number;
            /** @default false */
            require_anchor_for_commit: boolean;
            /** @default 10 */
            snapshot_retention: number;
        };
        Group: {
            id: string;
            name: string;
            plan: string;
            settings: components["schemas"]["GroupSettings"];
            /** Format: int64 */
            created_at: number;
        };
        GroupLimits: {
            max_nodes?: number | null;
            max_servers?: number | null;
            /** Format: int64 */
            max_storage_bytes?: number | null;
            /** Format: int64 */
            max_relay_bytes_month?: number | null;
        };
        Member: {
            user_id: string;
            email: string;
            display_name: string;
            role: components["schemas"]["Role"];
            /** Format: int64 */
            created_at: number;
        };
        Invite: {
            code: string;
            group_id: string;
            group_name: string;
            role: components["schemas"]["Role"];
            /** Format: int64 */
            expires_at: number | null;
            max_uses: number | null;
            uses: number;
        };
        EnrollmentToken: {
            id: string;
            group_id: string;
            anchor: boolean;
            hosting_enabled: boolean;
            labels?: {
                [key: string]: string;
            };
            /** Format: int64 */
            expires_at: number | null;
            max_uses?: number | null;
            uses: number;
        };
        EnrollmentTokenCreated: components["schemas"]["EnrollmentToken"] & {
            /** @description vde_… secret, shown once */
            token: string;
        };
        DeviceLink: {
            user_code: string;
            hostname: string;
            os: string;
            arch: string;
            agent_version?: string;
            /** @enum {string} */
            state: "pending" | "approved" | "consumed" | "expired";
            group_id?: string | null;
            node_id?: string | null;
            /** Format: int64 */
            expires_at: number;
        };
        Node: {
            id: string;
            group_id: string;
            name: string;
            /** @description base64 ed25519 */
            public_key: string;
            os: string;
            arch: string;
            agent_version?: string;
            hosting_enabled: boolean;
            anchor: boolean;
            priority?: number;
            max_memory_mb?: number | null;
            max_cpu_percent?: number | null;
            /** Format: int64 */
            max_storage_bytes?: number | null;
            /** @enum {string} */
            admin_state: "active" | "draining" | "disabled";
            /** @description computed from last_seen_at */
            online: boolean;
            /** @enum {string} */
            liveness?: "online" | "suspect" | "offline";
            /** Format: int64 */
            last_seen_at?: number | null;
            capabilities?: components["schemas"]["Capabilities"];
            /** @description mesh paths to other nodes in the group, from the node's latest heartbeat */
            connections: components["schemas"]["NodeConnection"][];
            /** Format: int64 */
            created_at: number;
        };
        NodeConnection: {
            node_id: string;
            name: string;
            /** @enum {string} */
            path: "none" | "direct" | "relayed";
            /** Format: int64 */
            rtt_us: number;
        };
        GameConfigField: {
            name: string;
            /** @enum {string} */
            type: "string" | "int" | "bool" | "select" | "secret";
            default?: unknown;
            /** @default false */
            required: boolean;
            /** @default false */
            secret: boolean;
            options?: string[];
            help?: string;
        };
        GamePort: {
            port: number;
            protocol: components["schemas"]["Protocol"];
        };
        Game: {
            id: string;
            name: string;
            ports: components["schemas"]["GamePort"][];
            os: ("linux" | "windows")[];
            arch: string[];
            min_memory_mb: number;
            runtimes?: string[];
            config_fields: components["schemas"]["GameConfigField"][];
        };
        /** @enum {string} */
        Protocol: "tcp" | "udp";
        /** @enum {string} */
        DesiredState: "running" | "stopped";
        /** @enum {string} */
        ObservedState: "stopped" | "starting" | "running" | "stopping" | "recovering" | "migrating" | "failed";
        ServerSummary: {
            hosting_on?: {
                node_id: string;
                name: string;
            } | null;
            latest_safe_save?: {
                snapshot_id: string;
                /** Format: int64 */
                created_at: number;
                replicas?: {
                    node_id: string;
                    name: string;
                    anchor: boolean;
                }[];
            } | null;
            latest_save?: {
                snapshot_id: string;
                /** Format: int64 */
                created_at: number;
            } | null;
            only_on_one_machine?: boolean;
            /** @example 127.77.12.34:25565 */
            address?: string;
            join_code?: string | null;
        };
        Server: {
            id: string;
            group_id: string;
            name: string;
            game_id: string;
            deployment_id?: string | null;
            desired_state: components["schemas"]["DesiredState"];
            observed_state: components["schemas"]["ObservedState"];
            /** Format: int64 */
            epoch: number;
            replication_factor: number;
            min_commit_replicas: number;
            snapshot_interval_s: number;
            preferred_node_id?: string | null;
            config: {
                [key: string]: unknown;
            };
            service?: components["schemas"]["Service"];
            summary: components["schemas"]["ServerSummary"];
            /** Format: int64 */
            created_at: number;
            /** Format: int64 */
            updated_at: number;
        };
        Service: {
            service_id: string;
            /** @example 127.77.12.34 */
            loopback_ip: string;
            ports: components["schemas"]["GamePort"][];
        };
        /** @enum {string} */
        ExecutionState: "preparing" | "restoring" | "starting" | "running" | "stopping" | "stopped" | "failed";
        Execution: {
            id: string;
            server_id: string;
            node_id: string;
            /** Format: int64 */
            epoch: number;
            state: components["schemas"]["ExecutionState"];
            /** @enum {string} */
            action: "run" | "stop";
            stop_reason?: string | null;
            /** Format: int64 */
            lease_expires_at?: number;
            restore_snapshot_id?: string | null;
            health?: string | null;
            message?: string | null;
            placement?: {
                score?: number;
                reasons?: string[];
            };
            /** Format: int64 */
            started_at?: number | null;
            /** Format: int64 */
            ended_at?: number | null;
            /** @enum {string|null} */
            end_reason?: "stopped" | "lost" | "failed" | "restore_failed" | "migrated" | "fenced" | null;
        };
        Snapshot: {
            id: string;
            server_id: string;
            /** Format: int64 */
            epoch: number;
            execution_id?: string;
            node_id: string;
            parent_id?: string | null;
            manifest_digest?: string;
            deployment_id?: string;
            /** @enum {string} */
            reason: "scheduled" | "manual" | "final" | "migration";
            /** @enum {string} */
            state: "local" | "replicating" | "committed" | "superseded" | "invalid";
            /** Format: int64 */
            size_bytes?: number;
            /** Format: int64 */
            stored_bytes?: number;
            file_count?: number;
            chunk_count?: number;
            pinned: boolean;
            /** Format: int64 */
            created_at: number;
            /** Format: int64 */
            committed_at?: number | null;
            replicas: {
                node_id: string;
                /** @enum {string} */
                state: "assigned" | "ready" | "deleting";
            }[];
        };
        LogLine: {
            /** Format: int64 */
            at: number;
            /** @enum {string} */
            stream: "stdout" | "stderr" | "agent";
            line: string;
        };
        Event: {
            /** Format: int64 */
            id: number;
            group_id: string;
            server_id?: string | null;
            node_id?: string | null;
            type: string;
            data?: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            created_at: number;
        };
        Capabilities: {
            os?: string;
            arch?: string;
            cpu_cores?: number;
            memory_total_mb?: number;
            memory_available_mb?: number;
            /** Format: int64 */
            disk_free_bytes?: number;
            on_battery?: boolean;
            user_active?: boolean;
            runtimes?: string[];
            cached_deployments?: string[];
            drivers?: string[];
            uptime_s?: number;
            /** Format: int64 */
            agent_started_at?: number;
            draining?: boolean;
        };
        MeshReport: {
            listen_port?: number;
            local_endpoints?: string[];
            observed_endpoints?: string[];
            relay_ids?: string[];
            peers?: {
                node_id?: string;
                /** @enum {string} */
                path?: "none" | "direct" | "relayed";
                /** Format: int64 */
                rtt_us?: number;
            }[];
        };
        ExecutionReport: {
            execution_id: string;
            server_id: string;
            /** Format: int64 */
            epoch: number;
            state: components["schemas"]["ExecutionState"];
            health?: string;
            message?: string;
            player_count?: number | null;
            join_code?: string;
        };
        AgentHeartbeat: {
            agent_version?: string;
            capabilities?: components["schemas"]["Capabilities"];
            mesh?: components["schemas"]["MeshReport"];
            executions?: components["schemas"]["ExecutionReport"][];
            /** Format: int64 */
            snapshots_stored_bytes?: number;
            /** @description Snapshot IDs deleted by this node per directive since its last acknowledged heartbeat. */
            deleted_snapshots?: string[];
        };
        DirectivePeer: {
            node_id: string;
            name: string;
            /** @description base64 ed25519 */
            public_key: string;
            endpoints?: string[];
            relay_ids?: string[];
        };
        DirectiveRoute: {
            service_id: string;
            server_id: string;
            server_name: string;
            loopback_ip: string;
            ports: components["schemas"]["GamePort"][];
            /** @description empty = server stopped */
            host_node_id?: string;
            /** Format: int64 */
            epoch?: number;
        };
        DirectiveRelay: {
            relay_id: string;
            addr: string;
            token: string;
        };
        ReplicationTask: {
            snapshot_id: string;
            server_id: string;
            manifest_digest: string;
            source_node_ids: string[];
        };
        SnapshotRequest: {
            request_id: string;
            /** @enum {string} */
            reason: "scheduled" | "manual" | "final" | "migration";
        };
        ExecutionDirective: {
            execution_id: string;
            server_id: string;
            server_name: string;
            /** Format: int64 */
            epoch: number;
            /** Format: int64 */
            lease_expires_at_unix_ms: number;
            /** @enum {string} */
            action: "run" | "stop";
            /** @enum {string|null} */
            stop_reason?: "user" | "migration" | "drain" | null;
            deployment?: {
                id: string;
                game_id: string;
                spec: {
                    [key: string]: unknown;
                };
            } | null;
            config?: {
                [key: string]: unknown;
            };
            service?: components["schemas"]["Service"];
            restore?: {
                snapshot_id: string;
                manifest_digest: string;
                source_node_ids: string[];
            } | null;
            snapshot_interval_s?: number;
            snapshot_requests?: components["schemas"]["SnapshotRequest"][];
        };
        AgentDirectives: {
            /** Format: int64 */
            server_time_unix_ms: number;
            heartbeat_interval_ms: number;
            lease_ttl_ms: number;
            node: {
                name: string;
                hosting_enabled: boolean;
                anchor: boolean;
                /** @enum {string} */
                admin_state: "active" | "draining" | "disabled";
            };
            executions?: components["schemas"]["ExecutionDirective"][];
            peers?: components["schemas"]["DirectivePeer"][];
            routes?: components["schemas"]["DirectiveRoute"][];
            relays?: components["schemas"]["DirectiveRelay"][];
            replication_tasks?: components["schemas"]["ReplicationTask"][];
            delete_snapshots?: string[];
        };
        DeviceEnrollRequest: {
            /** @description base64 ed25519 */
            public_key: string;
            hostname?: string;
            os?: string;
            arch?: string;
            agent_version?: string;
        };
        DeviceEnrollResponse: {
            device_code: string;
            /** @example WOLF-73-KITE */
            user_code: string;
            verification_url: string;
            expires_in: number;
            interval: number;
        };
        TokenEnrollRequest: {
            /** @description vde_… enrollment token */
            token: string;
            /** @description base64 ed25519 */
            public_key: string;
            hostname?: string;
            os?: string;
            arch?: string;
            agent_version?: string;
        };
        EnrollResult: {
            node_id: string;
            group_id: string;
            /** @description base64 ed25519 */
            control_plane_public_key: string;
        };
        AgentSnapshot: {
            snapshot_id: string;
            server_id: string;
            execution_id: string;
            /** Format: int64 */
            epoch: number;
            parent_id?: string | null;
            manifest_digest: string;
            deployment_id: string;
            /** @enum {string} */
            reason: "scheduled" | "manual" | "final" | "migration";
            /** Format: int64 */
            size_bytes?: number;
            /** Format: int64 */
            stored_bytes?: number;
            file_count?: number;
            chunk_count?: number;
            request_id?: string;
        };
    };
    responses: {
        /** @description Error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        GroupId: string;
        UserId: string;
        NodeId: string;
        ServerId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version string. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getRelayPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description base64 public key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelayPublicKey"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session created (also sets the varde_session cookie). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user and memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups the caller belongs to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        groups: components["schemas"]["Group"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created (caller becomes owner). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (owner only). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    settings?: components["schemas"]["GroupSettings"];
                };
            };
        };
        responses: {
            /** @description Updated (owner only). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members: components["schemas"]["Member"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Updated (owner only). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role?: components["schemas"]["Role"];
                    /** Format: int64 */
                    expires_at?: number;
                    max_uses?: number;
                };
            };
        };
        responses: {
            /** @description Invite created (admin+). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Joined the group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        group_id: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listEnrollmentTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens (hashes only; secrets shown at creation). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tokens: components["schemas"]["EnrollmentToken"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createEnrollmentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default false */
                    anchor?: boolean;
                    /** @default true */
                    hosting_enabled?: boolean;
                    labels?: {
                        [key: string]: string;
                    };
                    /** Format: int64 */
                    expires_at?: number;
                    max_uses?: number;
                };
            };
        };
        responses: {
            /** @description Created; `token` is shown only here. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTokenCreated"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    deleteEnrollmentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getDeviceLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device link status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLink"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    approveDeviceLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_code: string;
                    group_id: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Approved; the polling agent receives its node id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLink"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        nodes: components["schemas"]["Node"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    updateNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    hosting_enabled?: boolean;
                    anchor?: boolean;
                    priority?: number;
                    max_memory_mb?: number;
                    max_cpu_percent?: number;
                    /** Format: int64 */
                    max_storage_bytes?: number;
                    /** @enum {string} */
                    admin_state?: "active" | "draining" | "disabled";
                };
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        games: components["schemas"]["Game"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listServers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servers with computed summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        servers: components["schemas"]["Server"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    game_id: string;
                    config?: {
                        [key: string]: unknown;
                    };
                    replication_factor?: number;
                    min_commit_replicas?: number;
                    snapshot_interval_s?: number;
                    preferred_node_id?: string;
                };
            };
        };
        responses: {
            /** @description Created (admin+). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server with computed summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (admin+). Snapshots are retained per policy. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    updateServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    config?: {
                        [key: string]: unknown;
                    };
                    replication_factor?: number;
                    min_commit_replicas?: number;
                    snapshot_interval_s?: number;
                    preferred_node_id?: string;
                };
            };
        };
        responses: {
            /** @description Updated (admin+). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    startServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    preferred_node_id?: string;
                    /** @default false */
                    allow_older_snapshot?: boolean;
                };
            };
        };
        responses: {
            /** @description Start requested; reconciler places an execution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    stopServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stop requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    moveServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_node_id: string;
                };
            };
        };
        responses: {
            /** @description Migration requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshots with replica state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        snapshots: components["schemas"]["Snapshot"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    requestSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manual snapshot requested; delivered in the next heartbeat. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request_id: string;
                    };
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pinned: boolean;
                };
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listExecutions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        executions: components["schemas"]["Execution"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getServerLogs: {
        parameters: {
            query?: {
                execution_id?: string;
            };
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Captured stdout/stderr/agent lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lines: components["schemas"]["LogLine"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events after the given id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["Event"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream; honours Last-Event-ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminListGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All groups (operator only). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        groups: components["schemas"]["Group"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminSetGroupLimits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupLimits"];
            };
        };
        responses: {
            /** @description Limits set (null = unlimited). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupLimits"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    agentEnrollDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceEnrollRequest"];
            };
        };
        responses: {
            /** @description Codes issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceEnrollResponse"];
                };
            };
        };
    };
    agentEnrollDevicePoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    device_code: string;
                };
            };
        };
        responses: {
            /** @description Approved; node enrolled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResult"];
                };
            };
            /** @description Still pending user approval. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Expired. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agentEnrollToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenEnrollRequest"];
            };
        };
        responses: {
            /** @description Enrolled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResult"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    agentHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentHeartbeat"];
            };
        };
        responses: {
            /** @description Complete desired state for this node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDirectives"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    agentExecutionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    server_id: string;
                    /** Format: int64 */
                    epoch: number;
                    state: components["schemas"]["ExecutionState"];
                    health?: string;
                    message?: string;
                    join_code?: string;
                };
            };
        };
        responses: {
            /** @description Recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    agentExecutionLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    lines: components["schemas"]["LogLine"][];
                };
            };
        };
        responses: {
            /** @description Recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    agentCreateSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentSnapshot"];
            };
        };
        responses: {
            /** @description Snapshot registered; replication targets computed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    agentReplicaReady: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    state: "ready";
                };
            };
        };
        responses: {
            /** @description Replica marked ready; commit policy re-evaluated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
