[package]
name = "game-valheim"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1"
executor-api = { path = "../../crates/executor-api" }
game-driver-api = { path = "../../crates/game-driver-api" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
executor-native = { path = "../../crates/executor-native" }
runtimes = { path = "../../crates/runtimes" }
tempfile = "3"
